### PR TITLE
Fix config load from vendor

### LINKED ISSUE #58: Bug when loading config from a plugin
```php
$configFiles = current(array_filter([                                                                                       
    $dir . '/../../../../.xulieta.xml',
    $dir . '/../../../.xulieta.xml',
    $dir . '/../../.xulieta.xml',
    $dir . '/../.xulieta.xml',
    $dir . '/.xulieta.xml',
], 'is_file'));
```

### PR DESCRIPTION
**Pull request by malukenho**
Linking #58
Linking https://github.com/codelicia/xulieta-json/pull/6

### CODE REVIEW

File: src/Config/ConfigFile.php [hunk 1]
```diff
@@ -18,6 +18,7 @@ public static function loadInDirectory(string $dir): array
     {
         $configFiles = current(array_filter(
             [
+                $dir . '/../../../../.xulieta.xml',
```
Comment (szepeviktor) [inline src/Config/ConfigFile.php:21]: This looks like a pyramid scheme 🤣

**Review by szepeviktor — APPROVED** [review]

File: src/Config/ConfigFile.php (hunk 1 above)
Comment (szepeviktor) [reply src/Config/ConfigFile.php:21]: kép
